[package]
name = "web-service-api"
version = "0.1.0"
authors = ["Yuxi <645807+YuxiKou@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

redis = "0.19.0"
rand = "0.8.3"